import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter_firebase/auth/login.dart';
import 'package:flutter_firebase/auth/signup.dart';

// Generated by flutterfire configure

void main() async {
   WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp(

  );

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Login(),
      routes: {
        'signup': (context) => const Signup(),
        'login': (context) => const Login(),
      },
    );
  }
}


