import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter_firebase/auth/login.dart';
import 'package:flutter_firebase/auth/signup.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter_firebase/homepage.dart';


// Generated by flutterfire configure

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {

  @override
void initState() {
  super.initState(); // Always call this first
  FirebaseAuth.instance.authStateChanges().listen((User? user) {
    if (user == null) {
      print('User is currently signed out!');
    } else {
      print('User is signed in!');
    }
  });
}


  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: FirebaseAuth.instance.currentUser!= null && FirebaseAuth.instance.currentUser!.emailVerified
          ? const HomePage()
          : const Login(),
      routes: {
        'signup': (context) => const Signup(),
        'login': (context) => const Login(),
        'homepage': (context) => const HomePage(),
      },
    );
  }
}

